repos:
  - repo: local
    hooks:
      - id: detekt
        name: detekt
        entry: ./gradlew detekt
        language: system
        pass_filenames: false

      - id: compile
        name: compile
        entry: ./gradlew compileKotlin
        language: system
        pass_filenames: false