spring:
  application:
    name: ${APP_NAME}

  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  sql:
    init:
      mode: never

  liquibase:
    enabled: true
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    change-log: classpath:db/liquibase-changelog.yaml
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OIDC_ISSUER_URI}

  web:
    error:
      include-message: always

security:
  encryption:
    master-key: ${APP_MASTER_KEY}

tenant:
  name: Master
  alias: master

identityprovider:
  type: oidc
  name: ${OIDC_NAME}
  alias: ${OIDC_ALIAS}
  configurationEndpoint: ${OIDC_CLIENT_CONFIG_URL}
  clientId: ${OIDC_CLIENT_ID}
  clientSecret: ${OIDC_CLIENT_SECRET}

oidc:
  client-id: ${OIDC_CLIENT_ID}
  client-secret: ${OIDC_CLIENT_SECRET}
  user-info-endpoint: ${OIDC_USER_INFO}
  auth-url: ${OIDC_AUTH_URL}
  token-url: ${OIDC_TOKEN_URL}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    oauth:
      client-id: ${OIDC_CLIENT_ID}
      client-secret: ${OIDC_CLIENT_SECRET}
      scopes: ${OIDC_SCOPES}

logging:
  level:
    root: ${LOG_LEVEL}